// apps/app-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'nxext-demo-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'app-angular';
}

<header class="flex">
  <img alt="Nx logo" width="75" src="https://nx.dev/assets/images/nx-logo-white.svg" />
  <h1>Welcome to {{ title }}!</h1>
</header>
<main>
  <my-component first="a Web Component / Custom Element" middle="thanks" last="to Stencil"></my-component>
</main>

// apps/app-react/src/app/app.tsx
import React from 'react';

import './app.css';

import { ReactComponent as Logo } from './logo.svg';
import { MyComponent } from '@nxext-demo/my-library-react';

export const App = () => {
  /*
   * Replace the elements below with your own.
   *
   * Note: The corresponding styles are in the ./app.css file.
   */
  return (
    <div className="app">
      <header className="flex">
        <Logo width="75" height="75" />
        <h1>Welcome to app-react!</h1>
      </header>
      <main>
        <MyComponent first="a Web Component / Custom Element"
          middle="thanks"
          last="to Stencil" />
      </main>
    </div>
  );
};

export default App;
